
;; PROJECT EULER project 2
;; sum all the even fibonacci numbers under 4 million

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

;; Jeg tror tallet i er ute etter her er 1,485,607,536, ref regneark project002.gnumeric
;; i mappen ~/Playground/project-euler

;; Noen interessante observasjoner:
;; det 48. fibonacci-tallet er 4,807,526,976, og det 47. er 2,971,215,073
;; og hver tredje fibonaccinummer er et partall

#lang racket

